module.exports = {
    defaultRows: 5,
    defaultCols: 6,
    getTitle: function(levelData) {
        return levelData.titleSymbol + ' ' + levelData.name;
    },
    getLevel: function(n) {
        return this.data[n];
    },
    getRandomLevel: function() {
        var n = Math.floor(1 + Math.random() * (this.data.length - 1));
        return this.getLevel(n);
    },
    data: [
        {
            name: '',
            symbols: []
        },
        {
            name: 'Accessories',
            titleSymbol: '👛',
            cols: 4,
            rows: 3,
            symbols: [
                '👑',
                '💼',
                '👜',
                '👝',
                '👛',
                '👓',
                '🎀',
                '🌂',
                '💄'
            ]
        },
        {
            name: 'Flowers and trees',
            titleSymbol: '💐',
            cols: 4,
            rows: 4,
            symbols: [
                '💐',
                '🌸',
                '🌷',
                '🍀',
                '🌹',
                '🌻',
                '🌺',
                '🍁',
                '🍃',
                '🍂',
                '🌿',
                '🌾',
                '🌵',
                '🌴',
                '🌲',
                '🌳',
                '🌰',
                '🌼',
                '💮'
            ]
        },
        {
            name: 'Fruits and vegetables',
            titleSymbol: '🍏',
            cols: 5,
            rows: 4,
            symbols: [
                '🌰',
                '🌱',
                '🍎',
                '🍏',
                '🍊',
                '🍋',
                '🍒',
                '🍇',
                '🍉',
                '🍓',
                '🍑',
                '🍈',
                '🍌',
                '🍐',
                '🍍',
                '🍠',
                '🍆',
                '🍅',
                '🌽'
            ]
        },
        {
            name: 'Zodiac Signs',
            titleSymbol: '♋',
            cols: 6,
            rows: 4,
            symbols: [
                '♈',
                '♉',
                '♊',
                '♋',
                '♌',
                '♍',
                '♎',
                '♏',
                '♐',
                '♑',
                '♒',
                '♓',
                '⛎'
            ]
        },
        {
            name: 'Fashion',
            titleSymbol: '👗',
            symbols: [
                '🎩',
                '👒',
                '👟',
                '👞',
                '👡',
                '👠',
                '👢',
                '👕',
                '👔',
                '👚',
                '👗',
                '🎽',
                '👖',
                '👘',
                '👙'
            ]
        },
        {
            name: 'Buildings',
            titleSymbol: '🏢',
            symbols: [
                '🏠',
                '🏡',
                '🏫',
                '🏢',
                '🏣',
                '🏥',
                '🏦',
                '🏪',
                '🏩',
                '🏨',
                '💒',
                '⛪',
                '🏬',
                '🏤',
                '🌇',
                '🌆',
                '🏯',
                '🏰',
                '⛺',
                '🏭',
                '🗼',
                '🗾',
                '🗻',
                '🌄',
                '🌅',
                '🌃',
                '🗽',
                '🌉',
                '🎠',
                '🎡',
                '⛲',
                '🎢'
            ]
        },
        {
            name: 'Trains',
            titleSymbol: '🚄',
            symbols: [
                '🚂',
                '🚊',
                '🚉',
                '🚞',
                '🚆',
                '🚄',
                '🚅',
                '🚈',
                '🚇',
                '🚝',
                '🚋',
                '🚃'
            ]
        },
        {
            name: 'Hand Signs',
            titleSymbol: '👌',
            bg: false,
            symbols: [
                '👍',
                '👎',
                '👌',
                '👊',
                '✊',
                '✌',
                '👋',
                '✋',
                '👐',
                '👆',
                '👇',
                '👉',
                '👈',
                '🙌',
                '🙏',
                '☝',
                '👏',
                '💪'
            ]
        },
        {
            name: 'Arrows',
            titleSymbol: '↗',
            bg: false,
            symbols: [
                '⬇',
                '⬅',
                '➡',
                '↗',
                '↖',
                '↘',
                '↙',
                '↔',
                '↕',
                '🔄',
                '◀',
                '▶',
                '🔼',
                '🔽',
                '↩',
                '↪',
                '⏪',
                '⏩',
                '⏫',
                '⏬',
                '⤵',
                '⤴',
                '🔀',
                '🔃',
                '🔺',
                '🔻',
                '⬆'
            ]
        },
        {
            name: 'Technology',
            titleSymbol: '📀',
            symbols: [
                '🎥',
                '📷',
                '📹',
                '📼',
                '💿',
                '📀',
                '💽',
                '💾',
                '💻',
                '📱',
                '☎',
                '📞',
                '📟',
                '📠',
                '📡',
                '📺',
                '📻'
            ]
        },
        {
            name: 'Sport',
            titleSymbol: '🏀',
            symbols: [
                '🎯',
                '🏈',
                '🏀',
                '⚽',
                '⚾',
                '🎾',
                '🎱',
                '🏉',
                '🎳',
                '⛳',
                '🚵',
                '🚴',
                '🏁',
                '🏇',
                '🏆',
                '🎿',
                '🏂',
                '🏊',
                '🏄',
                '🎣'
            ]
        },
        {
            name: 'Games and Hobbies',
            titleSymbol: '🎨',
            symbols: [
                '🎨',
                '🎬',
                '🎤',
                '🎧',
                '🎼',
                '🎵',
                '🎶',
                '🎹',
                '🎻',
                '🎺',
                '🎷',
                '🎸',
                '👾',
                '🎮',
                '🃏',
                '🎴',
                '🀄',
                '🎲'
            ]
        }
    ]
};
